version: '2'
volumes:
  aegir_database:
services:
  hostmaster:
    image: aegir/hostmaster
    ports:
      - 81:80
    hostname: aegir.docker.local
    links:
      - database
    depends_on:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: root
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - aegir_database:/var/lib/mysql
